### ISSUE TITLE
Edit a label

### ISSUE THREAD

**Issue by GhaziTriki** [riadvice/hivelvet#23]
![labels list@2x](https://user-images.githubusercontent.com/4991088/161436317-cd252bdd-9fc2-4984-b94a-396864203e0f.png)

**Comment by SaoussenBlk** [comment]
@hanazarraa test if label name exists missing

**Comment by GhaziTriki** [comment]
@hanazarraa Can we please make the minimum length of the label name 1 letter? And description should be optional too.
