### ISSUE TITLE
When creating a preset and a label with uppercase letters, the popup remains stable

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/hivelvet#613]
**What is wrong with the current implementation? Please describe.**

When creating a preset and a label with uppercase letters, the popup remains stable

**Describe the solution you'd like**

The presets and labels page should appear 

**Screenshots/Designs**

![uppercase letters](https://user-images.githubusercontent.com/108723664/235971193-36131c91-2d7b-46f0-93e2-ef5f2d339f30.gif)

**Comment by GhaziTriki** [comment]
@marwa-benhassine Can we have a gif recordings please?

**Comment by marwa-benhassine** [comment]
okay

**Comment by marwa-benhassine** [comment]
@GhaziTriki done sir

**Comment by GhaziTriki** [comment]
We have to remove the lower case transformation for labels. Labels are assigned to users, we have no problem creating labels with duplicate names.
