### ISSUE TITLE
Edit the recording name through a meta property

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/hivelvet#771]
**Describe the bug**
 the name of the recording  is not saved 

**To Reproduce**

1. Go to the Recordings  page .
2. Click in the Edit button
3. Change the name of the recording  
4. Click the Save button

**Expected behavior**

 the name must be saved when changing .

**Screenshots**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/1af431c1-efba-46ce-8823-d8cd3e68fd36)

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome/Edge/Firefox/opera

**Comment by GhaziTriki** [comment]
The recording name is updated through a meta property.
