### ISSUE TITLE
Improve install.sh to detect non supported distro

### ISSUE THREAD

**Issue by hostbbb** [riadvice/hivelvet#821]
**What is wrong with the current implementation? Please describe.**
instahh.sh trys to install on any version of ubuntu.

**Describe the solution you'd like**
use  lsb_release -a to verify the distro is supported.    either stop or warn admin before proceeding.

22.10 had issues with percona and ppa packages.

**Comment by GhaziTriki** [comment]
Fixed in https://github.com/riadvice/bbbeasy/commit/dd182845c111fbd23c9b6604836791e1f4baba90
