### ISSUE TITLE
install.sh does not work on minimal Ubuntu Server due to missing packages

### ISSUE THREAD

**Issue by Ithanil** [riadvice/hivelvet#858]
**What is wrong with the current implementation? Please describe.**

The install.sh script fails on a vanilla Ubuntu Server 22.04 installation, because curl and software-properties-common are missing.

**Describe the solution you'd like**

Install curl and software-properties-common before executing the depending installation steps.

**Comment by GhaziTriki** [comment]
It looks like it is the same issue as this one https://github.com/riadvice/bbbeasy/issues/821 where we need better detection of the OS.

**Comment by GhaziTriki** [comment]
Looks not it is about missing packages.

**Comment by Ithanil** [comment]
No it is Jammy 22.04, as required. And yes, it ist about missing packages: curl is required in percona setup (before you would install it later in the install.sh script) and software-properties-common is needed for add-apt-repository.

**Comment by GhaziTriki** [comment]
Fixed in https://github.com/riadvice/bbbeasy/commit/6003427a8a467faad23b0ba6b3bd42a5986097c1
