### ISSUE TITLE
Cannot read property 'indexOf' in Translator.extractFromKey

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/hivelvet#976]
**Describe the bug**

When clicking the "Start" button, an error appears: TypeError: Cannot read properties of undefined (reading 'indexOf'). 

**To Reproduce**

1. Start the web app
2. Go to the room details page
3. Click on the start button

**Expected behavior**

The meeting must be opened when the start button is clicked

**Screenshots**

![image](https://github.com/user-attachments/assets/13fc7b79-cfd0-48ec-aff4-5aed7bcdc145)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment]
@marwa-benhassine please move it to #576
